name: WASM-

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

#      - name: Install Clippy
#        run:  rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu

#      - uses: actions/cache@v2
#        with:
#          path: |
#            ~/.cargo/registry/index/
#            ~/.cargo/registry/cache/
#            ~/.cargo/git/
#            ./target/
#          key: cargo-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
#          restore-keys: |
#            cargo-${{ runner.os }}-${{ github.job }}

      - name: Build
        run: cargo build

      - name: List Artifacts
        run: ls target/debug

      - name: Execute
        run: cargo run

#      - name: Lint
#        working-directory: ./packages/wasm/rs
#        run: cargo clippy

#      - name: Verify & Generate Documentation
#        working-directory: ./packages/wasm/rs
#        run: cargo doc --workspace --no-deps
